// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://himbcubhsogwejfwwjgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpbWJjdWJoc29nd2VqZnd3amdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODIyMzYsImV4cCI6MjA2ODA1ODIzNn0.u1cl3vsgc95Zchp72GZjv_Xu2f1k01bIoc4__0aMl0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});